# Generated by Django 2.2.6 on 2019-10-16 10:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fencerange', models.IntegerField(default='200')),
                ('color', models.CharField(default='red', max_length=30)),
                ('ringcolor', models.CharField(default='f03', max_length=30)),
                ('address', models.CharField(default='none', max_length=60)),
                ('warnning', models.CharField(blank=True, default='Silence Please', max_length=90, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=14)),
                ('mslink_dmr', models.BigIntegerField()),
                ('fname', models.CharField(max_length=32)),
                ('mapid', models.IntegerField()),
                ('name', models.CharField(max_length=33)),
                ('kind', models.CharField(max_length=11)),
                ('capacity', models.IntegerField()),
                ('operation_field', models.CharField(max_length=17)),
                ('recno', models.IntegerField()),
                ('fence', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=21)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('mineral_na', models.CharField(max_length=100)),
                ('mineral_1', models.CharField(max_length=100)),
                ('code_state', models.CharField(max_length=60)),
                ('et_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gener', models.CharField(max_length=33)),
                ('name', models.CharField(max_length=30)),
                ('Manufacturing', models.CharField(blank=True, max_length=50, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('age_status', models.CharField(blank=True, choices=[('Child', '-12'), ('adolescent', '12-15'), ('young man', '15-18'), ('adult', '18+')], default='adolescent', max_length=10)),
                ('watch', models.BooleanField(default=False)),
                ('mveimg', models.ImageField(upload_to='app1/images')),
            ],
        ),
        migrations.CreateModel(
            name='Tiser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='app1/images')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Movies')),
            ],
        ),
    ]
