# Generated by Django 2.2.6 on 2020-01-26 08:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='mveimg',
        ),
        migrations.AddField(
            model_name='movies',
            name='movieimg',
            field=models.ImageField(blank=True, null=True, upload_to='app1/images'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4236),
        ),
    ]
